// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniBlog.Data;

namespace MiniBlog.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MiniBlog.Shared.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("PostedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Joe Bloggs",
                            Post = "Lorem ipsum dolor sit amet...",
                            PostedDate = new DateTimeOffset(new DateTime(2020, 12, 29, 10, 48, 6, 887, DateTimeKind.Unspecified).AddTicks(6961), new TimeSpan(0, 7, 0, 0, 0)),
                            Title = "If only C# worked in the browser"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Joe Bloggs",
                            Post = "Lorem ipsum dolor sit amet...",
                            PostedDate = new DateTimeOffset(new DateTime(2021, 1, 3, 10, 48, 6, 891, DateTimeKind.Unspecified).AddTicks(6417), new TimeSpan(0, 7, 0, 0, 0)),
                            Title = "400th JS Framework released"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Joe Bloggs",
                            Post = "Lorem ipsum dolor sit amet...",
                            PostedDate = new DateTimeOffset(new DateTime(2021, 1, 8, 10, 48, 6, 891, DateTimeKind.Unspecified).AddTicks(6503), new TimeSpan(0, 7, 0, 0, 0)),
                            Title = "WebAssembly FTW"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Joe Bloggs",
                            Post = "Lorem ipsum dolor sit amet...",
                            PostedDate = new DateTimeOffset(new DateTime(2021, 1, 13, 10, 48, 6, 891, DateTimeKind.Unspecified).AddTicks(6512), new TimeSpan(0, 7, 0, 0, 0)),
                            Title = "Blazor is Awesome!"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Joe Bloggs",
                            Post = "Lorem ipsum dolor sit amet...",
                            PostedDate = new DateTimeOffset(new DateTime(2021, 1, 18, 10, 48, 6, 891, DateTimeKind.Unspecified).AddTicks(6516), new TimeSpan(0, 7, 0, 0, 0)),
                            Title = "Your first Blazor App"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
